# Generated by Django 3.2 on 2021-08-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210825_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MONITORS', 'Monitors')], default='MONITORS', max_length=50),
        ),
    ]
