# Generated by Django 3.2 on 2021-08-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_categorytemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytemplate',
            name='field_value',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
