# Generated by Django 3.2 on 2021-08-31 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_categorytemplate_field_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryTemplate',
        ),
    ]
