# Generated by Django 3.2 on 2021-09-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_categorytemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytemplate',
            name='field_value',
        ),
    ]
