# Generated by Django 3.2 on 2021-09-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristic',
            name='field_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productcharacteristic',
            name='field_value',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
