# Generated by Django 3.2 on 2021-09-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210911_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytemplate',
            name='for_filter',
            field=models.BooleanField(default=False),
        ),
    ]
