# Generated by Django 3.2 on 2021-09-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productcharacteristic_for_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristic',
            name='field_name',
            field=models.CharField(max_length=100),
        ),
    ]
