# Generated by Django 3.2 on 2021-09-25 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_productcharacteristic_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcharacteristic',
            name='for_filter',
        ),
        migrations.CreateModel(
            name='CategoryFilterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value', models.CharField(max_length=100)),
                ('category_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categorytemplate')),
            ],
        ),
    ]
