# Generated by Django 3.2.7 on 2021-10-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20211017_0914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
